AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 + API Gateway + Lambda + DynamoDB + Rekognition (end-to-end)
Globals:
 Function:
   Runtime: python3.11
   Timeout: 30
   MemorySize: 512
   Tracing: Active
   Environment:
     Variables:
       TABLE_NAME: !Ref ResultsTable
       UPLOAD_BUCKET: !Ref UploadBucket
Resources:
 UploadBucket:
   Type: AWS::S3::Bucket
   Properties:
     CorsConfiguration:
       CorsRules:
         - AllowedHeaders: ["*"]
           AllowedMethods: ["GET", "PUT", "POST", "HEAD"]
           AllowedOrigins: ["*"]
           MaxAge: 3000
 ResultsTable:
   Type: AWS::DynamoDB::Table
   Properties:
     BillingMode: PAY_PER_REQUEST
     AttributeDefinitions:
       - AttributeName: pk
         AttributeType: S
       - AttributeName: sk
         AttributeType: S
     KeySchema:
       - AttributeName: pk
         KeyType: HASH
       - AttributeName: sk
         KeyType: RANGE
 Api:
   Type: AWS::Serverless::Api
   Properties:
     StageName: prod
     Cors:
       AllowMethods: "'GET,POST,OPTIONS'"
       AllowHeaders: "'Content-Type'"
       AllowOrigin: "'*'"
 BackendFunction:
   Type: AWS::Serverless::Function
   Properties:
     CodeUri: src/
     Handler: app.lambda_handler
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref ResultsTable
       - S3WritePolicy:
           BucketName: !Ref UploadBucket
       - Statement:
           - Effect: Allow
             Action:
               - rekognition:DetectLabels
             Resource: "*"
     Events:
       GetUploadUrl:
         Type: Api
         Properties:
           RestApiId: !Ref Api
           Path: /upload-url
           Method: POST
       Analyze:
         Type: Api
         Properties:
           RestApiId: !Ref Api
           Path: /analyze
           Method: POST
       GetResult:
         Type: Api
         Properties:
           RestApiId: !Ref Api
           Path: /result
           Method: GET
Outputs:
 ApiBaseUrl:
   Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod"
 UploadBucketName:
   Value: !Ref UploadBucket
 ResultsTableName:
   Value: !Ref ResultsTable
